### ISSUE TITLE
Equality check always returns false even if schema didn't change

### ISSUE THREAD

**Issue by felixfbecker** [graphcool/graphql-cli#23]
I assume the schema returned by the GraphQL endpoint doesn't match the local schema when encoded, but is structurally identical.

**Comment by felixfbecker** [comment]
I added a `console.error()` into the `catch` block in get-schema.ts, which logs this error repeatadly:
```
Error
    at invariant (/Users/felix/src/github.com/graphcool/graphql-cli/node_modules/graphql/jsutils/invariant.js:19:11)
    at printType (/Users/felix/src/github.com/graphcool/graphql-cli/node_modules/graphql/utilities/schemaPrinter.js:151:83)
    at Array.map (<anonymous>)
    at printFilteredSchema (/Users/felix/src/github.com/graphcool/graphql-cli/node_modules/graphql/utilities/schemaPrinter.js:80:87)
    at Object.printSchema (/Users/felix/src/github.com/graphcool/graphql-cli/node_modules/graphql/utilities/schemaPrinter.js:44:10)
    at /Users/felix/src/github.com/graphcool/graphql-cli/dist/cmds/get-schema.js:72:58
    at step (/Users/felix/src/github.com/graphcool/graphql-cli/dist/cmds/get-schema.js:32:23)
    at Object.next (/Users/felix/src/github.com/graphcool/graphql-cli/dist/cmds/get-schema.js:13:53)
    at fulfilled (/Users/felix/src/github.com/graphcool/graphql-cli/dist/cmds/get-schema.js:4:58)
    at <anonymous>
```

**Comment by felixfbecker** [comment]
This is weird, I don't see this error anymore when I use `npm link` from my clone of the CLI, but when I install it in my project from npm, it happens. I think the reason why this happens is because my npm tree looks like this:
```
├─┬ gql2ts@1.2.1
│ ├─┬ @gql2ts/from-query@1.2.1
│ │ └── graphql@0.10.5
│ ├─┬ @gql2ts/from-schema@1.2.1
│ │ └── graphql@0.10.5  deduped
│ └─┬ @gql2ts/util@1.2.1
│   └── graphql@0.10.5  deduped
└─┬ graphql-cli@1.1.0
  ├── graphql@0.11.6
  ├─┬ graphql-config@1.0.6
  │ └── graphql@0.11.6
  └─┬ graphql-playground@0.0.6
    ├─┬ graphiql@0.11.5
    │ └─┬ codemirror-graphql@0.6.11
    │   └─┬ graphql-language-service-interface@0.0.19
    │     ├── graphql@0.10.5  deduped
    │     ├─┬ graphql-language-service-types@0.0.21
    │     │ └── graphql@0.10.5  deduped
    │     └─┬ graphql-language-service-utils@0.0.17
    │       └── graphql@0.10.5  deduped
    └── graphql@0.10.5  deduped
```
as you can see `graphql-config` and `graphql-cli` have both their own installation of `graphql` and `graphql`, so the schema produced by `config.getSchema()`and `graphql.getSchema()` are instances of different classes. `graphql` however does `instanceof` checks internally, which will always fail for that reason: https://sourcegraph.sgdev.org/github.com/graphql/graphql-js@master/-/blob/src/utilities/schemaPrinter.js#L150 (the worst part is that there is no error message)

There are multiple workarounds for this problem:
- Uninstall the other dependency on graphql, then reinstall this one first to get `graphql@16` at the top level. The problem is that the other dependency can have the same issue then.
- Shrinkwrap the dependencies of this module so achieve a deterministic install. Disadvantage is it would lock dependencies.
- Get graphql to stop using `instanceof`. This is the only viable long-term solution.

Related: https://github.com/avantcredit/gql2ts/issues/85
