### ISSUE TITLE
Can't Load ./cmd plugin:Error:

### ISSUE THREAD

**Issue by idkjs** [graphcool/graphql-cli#47]
Any idea what going on here? Is the package not up to date?

Installing graphql-cli in the project
Added .graphqlconfig:
```
{
  "schemaPath": "src/schema.graphql",
  "extensions": {
    "endpoints": {
      "dev": "https://api.graph.cool/relay/v1/cj9o4se940gsu0148s5aendpoint"
    }
  }
}
```
added script to package.json: ` "schema-dev": "graphql get-schema dev",`

ran `yarn run schema-dev`

got this error:
```
shingdev at cosmos in ~/code/REASON/fresh-relay-scripts
$ yarn schema-dev
yarn run v1.3.2
$ graphql get-schema dev
Can't load ./cmds plugin:Error: Cannot find module 'graphql-playground/middleware'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/graphql-cli/dist/cmds/playground.js:49:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
Usage: graphql [command]

Commands:
  load [--json] [--csv] [--endpoint]        Loads data from sources using
  [--mutation] [--mapping] [--delim]        mutations using .graphqlconfig

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Examples:
  graphql init            Interactively setup .graphqlconfig file
  graphql get-schema dev  Update local schema to match "dev" endpoint
  graphql diff dev prod   Show schema diff between "dev" and "prod" endpoints

For more information go to https://github.com/graphcool/graphql-cli

Too many non-option arguments: got 2, maximum of 1
Unknown arguments: get-schema, dev
✨  Done in 6.41s.
```

However, this works from command line:
```
get-graphql-schema https://api.graph.cool/relay/v1/cj9o4se940gsu0148s5aendpoint > ./schema.gql
```

**Comment by phaedryx** [comment]
I am getting a similar error

**Comment by akoutmos** [comment]
Same issue here. I reverted back to 1.1.0 and the error doesn't seem to occur.

**Comment by schickling** [comment]
Just release `1.1.2`. Could you please check again?

**Comment by idkjs** [comment]
1.1.2 update works as expected. Thank you, sir.
